# Generated by Django 5.2.5 on 2026-04-13 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0012_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kollabapp.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('link_url', models.URLField(blank=True, default='', max_length=500)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kollabapp.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_can_create_tasks', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_edit_tasks', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_delete_tasks', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='admin_only', max_length=20)),
                ('who_can_move_tasks', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_create_lists', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_edit_lists', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_delete_lists', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='admin_only', max_length=20)),
                ('who_can_attach_files', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('who_can_comment', models.CharField(choices=[('all_members', 'All Members'), ('admin_only', 'Admins Only')], default='all_members', max_length=20)),
                ('allow_due_dates', models.BooleanField(default=True)),
                ('allow_task_priorities', models.BooleanField(default=True)),
                ('allow_task_assignees', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_task_desc', models.BooleanField(default=True)),
                ('notify_on_task_create', models.BooleanField(default=True)),
                ('notify_on_task_done', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('notify_on_assign', models.BooleanField(default=True)),
                ('max_tasks_per_list', models.PositiveIntegerField(default=0)),
                ('max_lists', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskboard_settings_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskboard_settings', to='kollabapp.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kollabapp.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#60a5fa', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to='kollabapp.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kollabapp.tasklist'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('chat', 'Workspace Chat'), ('dm', 'Direct Message'), ('taskboard', 'Taskboard')], max_length=20)),
                ('notification_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kollabapp.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'user', 'is_read'], name='kollabapp_n_workspa_e07068_idx')],
            },
        ),
    ]
