# Generated by Django 5.2.5 on 2026-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0013_task_taskattachment_taskboardsettings_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
