# Generated by Django 5.2.5 on 2026-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0016_otpverification_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
