# Generated by Django 5.2.5 on 2026-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0017_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/dm/'),
        ),
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/workspace/'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
