# Generated by Django 5.2.5 on 2026-06-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0018_directmessage_duration_directmessage_voice_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='voice_note',
            field=models.CharField(blank=True, help_text='Supabase or local storage path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_note',
            field=models.CharField(blank=True, help_text='Supabase or local storage path', max_length=500, null=True),
        ),
    ]
