# Generated by Django 5.2.5 on 2026-06-06 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0019_alter_directmessage_voice_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=500)),
                ('file_url', models.TextField(blank=True, default='')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Bytes')),
                ('file_category', models.CharField(default='document', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='kollabapp.directmessage')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='kollabapp.message')),
                ('receiver', models.ForeignKey(blank=True, help_text='Only set for DM files', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chat_files', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_files', to='kollabapp.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
