# Generated by Django 5.2.5 on 2026-06-06 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0020_chatfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200, unique=True)),
                ('room_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], default='video', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='kollabapp.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
