# Generated by Django 5.2.5 on 2026-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0022_aimessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
