# Generated by Django 5.2.5 on 2026-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0023_delete_otpverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['workspace'], name='kollabapp_d_workspa_b95bee_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender'], name='kollabapp_d_sender__a2f146_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['receiver'], name='kollabapp_d_receive_1aea44_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['created_at'], name='kollabapp_d_created_c76238_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['workspace', 'sender', 'receiver', 'created_at'], name='kollabapp_d_workspa_423a61_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['workspace', 'receiver', 'sender', 'created_at'], name='kollabapp_d_workspa_b1a8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['workspace'], name='kollabapp_m_workspa_b5f8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='kollabapp_m_sender__509fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='kollabapp_m_created_55c836_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_uuid'], name='kollabapp_m_message_c0b2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['workspace', 'created_at', 'id'], name='kollabapp_m_workspa_13195f_idx'),
        ),
    ]
