# Generated by Django 5.2.5 on 2026-06-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0026_workspacejoinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceJoinRequest',
        ),
    ]
