# Generated by Django 5.2.5 on 2025-08-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollabapp', '0004_workspacemembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('title', 'admin')},
        ),
    ]
